// This file is generated by generator/generate-build-info.mjs.
// It is committed with a baseline value so TypeScript can compile before the first generated build.

export const buildInfo = {
    "appVersion": "0.6.6",
    "packageVersion": "0.6.6",
    "versionCode": "400015",
    "gitSha": "354b64ffe93b4a6efe3f2737b97ef99e86747b91",
    "shortSha": "354b64f",
    "gitRef": "feat/mpv-player",
    "gitRefType": "branch",
    "buildRunUrl": "",
    "buildDate": "2026-07-07T15:18:22.513Z",
    "signing": "configured",
    "node": "v24.15.0",
    "react": "19.2.3",
    "reactNative": "0.85.3",
    "expo": "56.0.8",
    "nitroPlayer": "1.4.3",
} as const;

export type BuildInfo = typeof buildInfo;
