// This file is generated by generator/generate-build-info.mjs.
// It is committed with a baseline value so TypeScript can compile before the first generated build.

export const buildInfo = {
    "appVersion": "0.7.2",
    "packageVersion": "0.7.2",
    "versionCode": "400021",
    "gitSha": "266454012d6d7f73e3386c3cce53b24fe29cbf63",
    "shortSha": "2664540",
    "gitRef": "feat/mpv-player",
    "gitRefType": "branch",
    "buildRunUrl": "",
    "buildDate": "2026-07-19T08:21:09.235Z",
    "signing": "configured",
    "node": "v24.15.0",
    "react": "19.2.3",
    "reactNative": "0.85.3",
    "expo": "56.0.8",
    "nitroPlayer": "1.4.3",
} as const;

export type BuildInfo = typeof buildInfo;
