// This file is generated by generator/generate-build-info.mjs.
// It is committed with a baseline value so TypeScript can compile before the first generated build.

export const buildInfo = {
    "appVersion": "0.6.5-nitro.1",
    "packageVersion": "0.6.5-nitro.1",
    "versionCode": "400014",
    "gitSha": "0ddf399870a2fc9fd4ab4eed9eb9557d922884fb",
    "shortSha": "0ddf399",
    "gitRef": "codex/plugin-center-mvp",
    "gitRefType": "branch",
    "buildRunUrl": "",
    "buildDate": "2026-06-09T13:34:08.788Z",
    "signing": "configured",
    "node": "v24.15.0",
    "react": "19.2.3",
    "reactNative": "0.85.3",
    "expo": "56.0.8",
    "nitroPlayer": "^1.4.1"
} as const;

export type BuildInfo = typeof buildInfo;
