name: 自动构建安卓应用

on:
  workflow_dispatch: # 允许手动触发
  pull_request:
    types:
      - closed # 当 Pull Request 关闭时触发

jobs:
  build-android:
    runs-on: ubuntu-latest # 直接指定运行环境
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 设置 Java (JDK) 环境
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 配置 Gradle 缓存
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: 安装 Node.js 依赖
        run: npm install

      - name: 获取应用版本号
        id: get_version
        run: echo "APP_VERSION=$(node -p -e 'require("./package.json").version')" >> $GITHUB_ENV

      - name: 动态生成签名密钥库和 keystore.properties
        run: |
          echo "动态生成签名密钥..."
          keytool -genkey -v \
            -keystore release.jks \
            -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" \
            -alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
            -keypass "${{ secrets.RELEASE_KEY_PASSWORD }}" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=MusicFree Workflow, OU=Dev, O=GitHub Actions, L=CI, ST=CI, C=US"

          echo "创建 keystore.properties..."
          echo "RELEASE_STORE_FILE=../../release.jks" > android/keystore.properties
          echo "RELEASE_STORE_PASSWORD=${{ secrets.RELEASE_STORE_PASSWORD }}" >> android/keystore.properties
          echo "RELEASE_KEY_ALIAS=${{ secrets.RELEASE_KEY_ALIAS }}" >> android/keystore.properties
          echo "RELEASE_KEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}" >> android/keystore.properties
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

      - name: 赋予 Gradle Wrapper 执行权限
        run: chmod +x ./android/gradlew

      - name: 构建 Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease --no-daemon

      - name: 查找构建的 APK 文件
        id: find_apk
        run: |
          APK_PATH=$(find ./android/app/build/outputs/apk/release -name '*.apk' | head -n 1)
          echo "APK_PATH=${APK_PATH}" >> $GITHUB_ENV
          if [ -z "${APK_PATH}" ]; then
            echo "错误：未找到构建的 APK 文件。"
            exit 1
          fi

      - name: 上传构建产物 (APK)
        uses: actions/upload-artifact@v4
        with:
          name: MusicFree-v${{ env.APP_VERSION }}-${{ github.sha }}
          path: ${{ env.APK_PATH }}
          if-no-files-found: error
