# .github/workflows/generate-keystore.yml
name: Generate Android Keystore

on:
  workflow_dispatch: # 允许手动触发

jobs:
  generate-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Java (JDK) 环境
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 动态生成签名密钥库和 keystore.properties
        id: generate_keys
        run: |
          KEYSTORE_FILENAME="release.jks"
          PROPERTIES_FILENAME="keystore.properties"
          STORE_PASSWORD="${{ secrets.NEW_RELEASE_STORE_PASSWORD || 'your-default-store-password' }}" # 从 Secret 或使用默认值
          KEY_ALIAS="${{ secrets.NEW_RELEASE_KEY_ALIAS || 'your-default-key-alias' }}"       # 从 Secret 或使用默认值
          KEY_PASSWORD="${{ secrets.NEW_RELEASE_KEY_PASSWORD || 'your-default-key-password' }}" # 从 Secret 或使用默认值

          echo "动态生成签名密钥库 ($KEYSTORE_FILENAME)..."
          keytool -genkey -v \
            -keystore $KEYSTORE_FILENAME \
            -storepass "$STORE_PASSWORD" \
            -alias "$KEY_ALIAS" \
            -keypass "$KEY_PASSWORD" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Your App Name, OU=Dev, O=Your Org, L=City, ST=State, C=Country" # 请替换为你的信息

          echo "创建 $PROPERTIES_FILENAME..."
          echo "RELEASE_STORE_FILE=../../$KEYSTORE_FILENAME" > $PROPERTIES_FILENAME # 注意路径
          echo "RELEASE_STORE_PASSWORD=$STORE_PASSWORD" >> $PROPERTIES_FILENAME
          echo "RELEASE_KEY_ALIAS=$KEY_ALIAS" >> $PROPERTIES_FILENAME
          echo "RELEASE_KEY_PASSWORD=$KEY_PASSWORD" >> $PROPERTIES_FILENAME

          echo "::set-output name=keystore_filename::$KEYSTORE_FILENAME"
          echo "::set-output name=properties_filename::$PROPERTIES_FILENAME"
        env:
          # 在这里定义用于首次生成的密码和别名，或者从 Secrets 读取 (如果已设置)
          # 强烈建议首次生成时使用临时的强密码，然后将其安全保存
          NEW_RELEASE_STORE_PASSWORD: ${{ secrets.YOUR_DESIRED_STORE_PASSWORD }}
          NEW_RELEASE_KEY_ALIAS: ${{ secrets.YOUR_DESIRED_KEY_ALIAS }}
          NEW_RELEASE_KEY_PASSWORD: ${{ secrets.YOUR_DESIRED_KEY_PASSWORD }}

      - name: 上传生成的密钥文件
        uses: actions/upload-artifact@v4
        with:
          name: android-signing-keys
          path: |
            ${{ steps.generate_keys.outputs.keystore_filename }}
            ${{ steps.generate_keys.outputs.properties_filename }}
